# Principal Component Analysis (PCA)
# Introduction and Walkthrough adapted
# (original by "Luke Hayden" taken from https://www.datacamp.com/tutorial/pca-analysis-r)

# inspect the data
head(mtcars, 5)


######################################
# Info about variables
# *mpg: Fuel consumption (Miles per (US) gallon): more powerful and heavier cars tend to consume more fuel.

# *cyl: Number of cylinders: more powerful cars often have more cylinders

# *disp: Displacement (cu.in.): the combined volume of the engine's cylinders

# *hp: Gross horsepower: this is a measure of the power generated by the car

# *drat: Rear axle ratio: this describes how a turn of the drive shaft corresponds to a turn of the wheels. Higher values will decrease fuel efficiency.

# *wt: Weight (1000 lbs): pretty self-explanatory!

# *qsec: 1/4 mile time: the cars speed and acceleration

# *vs: Engine block: this denotes whether the vehicle's engine is shaped like a "V", or is a more common straight shape.

# *am: Transmission: this denotes whether the car's transmission is automatic (0) or manual (1).

# *gear: Number of forward gears: sports cars tend to have more gears.

# *carb: Number of carburetors: associated with more powerful engines

##########


# as PCA works best with numerical data, you'll exclude the 2 catergorical 
# variables (vs and am). Pass the rest of the matrix to the prcomp() fuction
# and assign resutls to mtcars.pca.
# set "center" and "scale" = TRUE
??pcrcomp
mtcars.pca <- prcomp(mtcars[,c(1:7,10,11)], center = TRUE,scale. = TRUE)

# summary about the pricipal components
summary(mtcars.pca)
# first two components add 87% of variance

str(mtcars.pca)

# str() contains following information about the PCA
# - center point ($center), scaling ($scale), standard deviation(sdev)
# - relationship (correlation or anticorrelation, etc.) between initial 
#   variables and the pricipal components ($rotation)
# - The values of each sample in terms of the principal components ($x)


#############################
# Plotting PCA
#####

# install library if necessary
install.packages("devtools")
# load library
library(devtools)

# package "remotes" necessary to install "ggbiplot"
install.packages("remotes")
remotes::install_github("vqv/ggbiplot")
# load library
library(ggbiplot)

# overview
ggbiplot(mtcars.pca)

# assign names to datapoints
ggbiplot(mtcars.pca, labels=rownames(mtcars))

###############
# Interpretation of results
##

mtcars.country <- c(rep("Japan",3), rep("US",4), rep("Europe",7), rep("US",3), 
                    "Europe", rep("Japan", 3), rep("US",4), rep("Europe", 3), 
                    "US", rep("Europe", 3))

ggbiplot(mtcars.pca,ellipse=TRUE,  labels=rownames(mtcars), groups=mtcars.country)
# describe what you see: 
#    - US cars appear to have higher values for "cyl", "disp" and "wt"
#    - Japanese cars have higher "mpg"
#    - European cars are not so thight clustered

# look at PC3 and PC4 
ggbiplot(mtcars.pca,ellipse=TRUE,choices=c(3,4),   labels=rownames(mtcars), groups=mtcars.country)
# decribe what you see:
#    - in PC3 and PC4 cars are overlapping in the center and only contribute very 
#      little to variance 


# adjust Graphical Parameters

# add circle to plot
ggbiplot(mtcars.pca,ellipse=TRUE,circle=TRUE, labels=rownames(mtcars), groups=mtcars.country)

# remove arrows
ggbiplot(mtcars.pca,ellipse=TRUE,obs.scale = 1, var.scale = 1,var.axes=FALSE,   labels=rownames(mtcars), groups=mtcars.country)

## Customize ggbiplot
# specify colour ->  scale_colour_manual()
# add title -> ggtitle()
# specify minimal() theme -> minimal()
# move legend -> theme()

ggbiplot(mtcars.pca,ellipse=TRUE,obs.scale = 1, var.scale = 1,  labels=rownames(mtcars), groups=mtcars.country) +
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "dark blue"))+
  ggtitle("PCA of mtcars dataset")+
  theme_minimal()+
  theme(legend.position = "bottom")


################################
# Adding a new sample
######
spacecar <- c(1000,60,50,500,0,0.5,2.5,0,1,0,0)

mtcarsplus <- rbind(mtcars, spacecar)
mtcars.countryplus <- c(mtcars.country, "Jupiter")

mtcarsplus.pca <- prcomp(mtcarsplus[,c(1:7,10,11)], center = TRUE,scale. = TRUE)

ggbiplot(mtcarsplus.pca, obs.scale = 1, var.scale = 1, ellipse = TRUE, circle = FALSE, var.axes=TRUE, labels=c(rownames(mtcars), "spacecar"), groups=mtcars.countryplus)+
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "violet", "dark blue"))+
  ggtitle("PCA of mtcars dataset, with extra sample added")+
  theme_minimal()+
  theme(legend.position = "bottom")


# Result looks very skewed -> Try projection of sample to existing PCA!


##########################
# Project a New Sample onto the Original PCA
######################

# introduce spacecar
spacecar <- c(1000,60,50,500,0,0.5,2.5,0,1,0,0)
mtcars.countryplus <- c(mtcars.country, "Jupiter")


# scale spacecar compared to means of mtcars 
# (to obtain proportions)
s.sc <- scale(t(spacecar[c(1:7,10,11)]), center= mtcars.pca$center)

# apply rotation of mtcars.pca to spacecars
s.pred <- s.sc %*% mtcars.pca$rotation


mtcars.plusproj.pca <- mtcars.pca
mtcars.plusproj.pca$x <- rbind(mtcars.plusproj.pca$x, s.pred)


ggbiplot(mtcars.plusproj.pca, obs.scale = 1, var.scale = 1, ellipse = TRUE, circle = FALSE, var.axes=TRUE, labels=c(rownames(mtcars), "spacecar"), groups=mtcars.countryplus)+
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "violet", "dark blue"))+
  ggtitle("PCA of mtcars dataset, with extra sample projected")+
  theme_minimal()+
  theme(legend.position = "bottom")

# spacecar seems to not fit to any of the existing groups


# But which is better, the projection or the recomputation of the PCA?
#     It depends somewhat on the question that you are trying to answer; 
#     the recomputation shows that spacecar is an outlier, the projection 
#     tells you that you can't place it in one of the existing groups. 
#     Performing both approaches is often useful when doing exploratory 
#     data analysis by PCA. This type of exploratory analysis is often 
#     a good starting point before you dive more deeply into a dataset. 
#     Your PCAs tell you which variables separate American cars from 
#     others and that spacecar is an outlier in our dataset. 
#     A possible next step would be to see if these relationships hold 
#     true for other cars or to see how cars cluster by marque or by type 
#     (sports cars, 4WDs, etc).


